# Generated by Django 6.0.2 on 2026-02-06 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
            ],
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Localidade')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Série/Ano')),
                ('nivel_ensino', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nível de Ensino')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Manual')),
                ('inep', models.CharField(max_length=10, unique=True, verbose_name='Código INEP')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Escola')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('bairrodistrito', models.CharField(max_length=100, verbose_name='Bairro/Distrito')),
                ('gestor', models.CharField(max_length=255, verbose_name='Gestor (Nome e Telefone)')),
                ('telefone_extraido', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Extraído')),
                ('dados', models.JSONField(blank=True, null=True, verbose_name='Dados Adicionais')),
                ('localidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localidade', verbose_name='Localidade')),
            ],
        ),
        migrations.CreateModel(
            name='EvolucaoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_inicial', models.IntegerField(verbose_name='Ano Inicial')),
                ('ano_final', models.IntegerField(verbose_name='Ano Final')),
                ('crescimento_proficiencia', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Crescimento Proficiência')),
                ('crescimento_adequado_avancado', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Crescimento % Adequado+Avançado')),
                ('classificacao_evolucao', models.CharField(choices=[('alta', 'Alta Evolução'), ('moderada', 'Evolução Moderada'), ('estavel', 'Estabilidade'), ('regressao', 'Regressão')], max_length=50, verbose_name='Classificação da Evolução')),
                ('data_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cálculo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucao', to='core.escola', verbose_name='Escola')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie', verbose_name='Série/Ano')),
            ],
            options={
                'verbose_name': 'Evolução da Escola',
                'verbose_name_plural': 'Evoluções das Escolas',
            },
        ),
        migrations.CreateModel(
            name='MetaMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('proficiencia_meta', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Meta de Proficiência')),
                ('percentual_adequado_avancado_meta', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Meta % Adequado+Avançado')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Meta')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie', verbose_name='Série/Ano')),
            ],
            options={
                'verbose_name': 'Meta Municipal',
                'verbose_name_plural': 'Metas Municipais',
                'unique_together': {('ano', 'disciplina', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='DesempenhoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano da Prova')),
                ('alunos_previstos', models.IntegerField(verbose_name='Alunos Previstos')),
                ('alunos_avaliados', models.IntegerField(verbose_name='Alunos Avaliados')),
                ('percentual_avaliados', models.DecimalField(decimal_places=2, help_text='Percentual de alunos avaliados', max_digits=5, verbose_name='Avaliados (%)')),
                ('proficiencia_media', models.DecimalField(decimal_places=2, help_text='Média de proficiência da escola', max_digits=6, verbose_name='Proficiência Média')),
                ('abaixo_basico', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Abaixo do Básico (%)')),
                ('basico', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Básico (%)')),
                ('adequado', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Adequado (%)')),
                ('avancado', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Avançado (%)')),
                ('taxa_participacao', models.DecimalField(blank=True, decimal_places=2, help_text='Taxa calculada: (avaliados/previstos)*100', max_digits=5, null=True, verbose_name='Taxa de Participação (%)')),
                ('meta_estabelecida', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Meta Estabelecida')),
                ('variacao_ano_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Variação vs Ano Anterior')),
                ('posicao_municipio', models.IntegerField(blank=True, null=True, verbose_name='Posição no Município')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='core.escola', verbose_name='Escola')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie', verbose_name='Série/Ano')),
            ],
            options={
                'verbose_name': 'Desempenho da Escola',
                'verbose_name_plural': 'Desempenhos das Escolas',
                'ordering': ['-ano', 'escola__nome', 'disciplina__nome'],
                'unique_together': {('escola', 'ano', 'disciplina', 'serie')},
            },
        ),
    ]
