# Generated by Django 6.0.2 on 2026-02-24 15:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esfera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Esfera')),
            ],
            options={
                'verbose_name': 'Esfera',
                'verbose_name_plural': 'Esferas',
            },
        ),
        migrations.CreateModel(
            name='DesempenhoEsfera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano da Prova')),
                ('alunos_previstos', models.PositiveIntegerField(verbose_name='Alunos Previstos')),
                ('alunos_avaliados', models.PositiveIntegerField(verbose_name='Alunos Avaliados')),
                ('percentual_avaliados', models.DecimalField(decimal_places=2, help_text='Percentual de alunos avaliados (calculado automaticamente)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avaliados (%)')),
                ('proficiencia_media', models.DecimalField(decimal_places=2, help_text='Média de proficiência da esfera', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Proficiência Média')),
                ('abaixo_basico', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Abaixo do Básico (%)')),
                ('basico', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Básico (%)')),
                ('adequado', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Adequado (%)')),
                ('avancado', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avançado (%)')),
                ('meta_estabelecida', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Meta Estabelecida')),
                ('variacao_ano_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Variação vs Ano Anterior')),
                ('posicao_municipio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Posição no Município')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos_esfera', to='core.disciplina', verbose_name='Disciplina')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos_esfera', to='core.serie', verbose_name='Série/Ano')),
                ('esfera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='core.esfera', verbose_name='Esfera')),
            ],
            options={
                'verbose_name': 'Desempenho da Esfera',
                'verbose_name_plural': 'Desempenhos das Esferas',
                'ordering': ['-ano', 'esfera__nome', 'disciplina__nome'],
                'indexes': [models.Index(fields=['esfera', 'ano', 'disciplina', 'serie'], name='core_desemp_esfera__34bf47_idx')],
                'unique_together': {('esfera', 'ano', 'disciplina', 'serie')},
            },
        ),
    ]
