# Generated by Django 6.0.2 on 2026-02-27 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_esfera_desempenhoesfera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_habilidade', models.CharField(help_text='Código identificador da habilidade (ex: EF05LP01)', max_length=20, verbose_name='Código da Habilidade')),
                ('dc_habilidade', models.TextField(help_text='Descrição completa da habilidade', verbose_name='Descrição da Habilidade')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie', verbose_name='Série/Ano')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['disciplina', 'serie', 'cd_habilidade'],
                'unique_together': {('serie', 'disciplina', 'cd_habilidade')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('cd_habilidade', models.CharField(max_length=20, verbose_name='Código da Habilidade')),
                ('tx_acerto', models.DecimalField(decimal_places=2, help_text='Percentual de acerto para esta habilidade', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taxa de Acerto (%)')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina')),
                ('esfera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.esfera', verbose_name='Esfera')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie', verbose_name='Série/Ano')),
            ],
            options={
                'verbose_name': 'Resultado de Habilidade',
                'verbose_name_plural': 'Resultados de Habilidades',
                'ordering': ['-ano', 'esfera', 'disciplina', 'serie', 'cd_habilidade'],
                'indexes': [models.Index(fields=['ano', 'esfera', 'serie', 'disciplina'], name='core_result_ano_031d6c_idx')],
                'unique_together': {('ano', 'esfera', 'serie', 'disciplina', 'cd_habilidade')},
            },
        ),
    ]
