# Generated by Django 6.0.2 on 2026-03-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_habilidade1_resultadohabilidade1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadohabilidade1',
            name='habilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.habilidade1', verbose_name='Habilidade'),
        ),
    ]
