# Generated by Django 6.0.2 on 2026-03-20 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hab_resulthab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoHabEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('tx_acerto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de Acerto (%)')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escola', verbose_name='Escola')),
                ('hab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hab', verbose_name='Habilidade')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie', verbose_name='Série/Ano')),
            ],
            options={
                'indexes': [models.Index(fields=['ano', 'escola', 'serie', 'disciplina'], name='core_result_ano_a48c23_idx')],
                'unique_together': {('ano', 'escola', 'serie', 'disciplina', 'hab')},
            },
        ),
    ]
