# Generated by Django 6.0.2 on 2026-04-14 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resultadohabescola'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPreliminarSaeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('alunos_previstos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alunos Previstos')),
                ('alunos_avaliados', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alunos Avaliados')),
                ('taxa_participacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taxa de Participação (%)')),
                ('media_lp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Média Língua Portuguesa')),
                ('media_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Média Matemática')),
                ('media_geral', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Média Geral')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_preliminares', to='core.escola', verbose_name='Escola')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie', verbose_name='Série/Ano')),
            ],
            options={
                'verbose_name': 'Resultado Preliminar SAEB',
                'verbose_name_plural': 'Resultados Preliminares SAEB',
                'ordering': ['-ano', 'escola__nome'],
                'indexes': [models.Index(fields=['ano'], name='core_result_ano_2dac50_idx'), models.Index(fields=['escola', 'ano'], name='core_result_escola__cfba88_idx'), models.Index(fields=['ano', 'serie'], name='core_result_ano_05869f_idx')],
                'unique_together': {('escola', 'serie', 'ano')},
            },
        ),
    ]
