# Generated by Django 6.0.2 on 2026-04-14 20:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_resultpreliminarsaeb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPreliminarSaeb_2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('alunos_previstos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('alunos_avaliados', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('taxa_participacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taxa_aprovacao', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('media_lp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('media_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('media_geral', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ideb_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_preliminares_2025', to='core.escola')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie')),
            ],
            options={
                'ordering': ['-ano'],
                'unique_together': {('escola', 'serie', 'ano')},
            },
        ),
    ]
