# Generated by Django 6.0.2 on 2026-04-30 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_escola_latitude_escola_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alfabetometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de Referência')),
                ('periodo', models.CharField(blank=True, help_text='Ex: 1º Semestre, 2023/2024, etc.', max_length=50, null=True, verbose_name='Período')),
                ('qtd_alunos_ano', models.IntegerField(default=0, verbose_name='Total de Alunos no Ano')),
                ('qtd_pre_silabico', models.IntegerField(default=0, verbose_name='Alunos Pré-Silábicos')),
                ('qtd_silabico', models.IntegerField(default=0, verbose_name='Alunos Silábicos')),
                ('qtd_silabico_alfabetico', models.IntegerField(default=0, verbose_name='Alunos Silábico-Alfabéticos')),
                ('qtd_alfabetico', models.IntegerField(default=0, verbose_name='Alunos Alfabéticos')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alfabetometro_data', to='core.escola', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Dados do Alfabetômetro',
                'verbose_name_plural': 'Dados do Alfabetômetro',
                'unique_together': {('escola', 'ano_referencia', 'periodo')},
            },
        ),
    ]
