# Generated by Django 6.0.2 on 2026-05-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alfabetometro'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEscrita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Nível de Escrita')),
            ],
            options={
                'verbose_name': 'Nível de Escrita',
                'verbose_name_plural': 'Níveis de Escrita',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Estudante')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('periodo', models.CharField(blank=True, help_text='Ex: Manhã, Tarde, Noite', max_length=50, null=True, verbose_name='Período')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano de Referência')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudantes', to='core.escola', verbose_name='Escola')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudantes', to='core.serie', verbose_name='Série/Ano')),
                ('nivel_escrita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes', to='core.nivelescrita', verbose_name='Nível de Escrita')),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['escola', 'serie', 'ano'], name='core_estuda_escola__ad0390_idx'), models.Index(fields=['nivel_escrita'], name='core_estuda_nivel_e_79d5c7_idx')],
            },
        ),
    ]
